### ISSUE TITLE
🐛 BUG: pnpm wrangler pages functions build wraps generated bundle with form-data headers

### ISSUE THREAD

**Issue by istarkov** [cloudflare/workers-sdk#3065]
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.16.0

### What operating system are you using?

Mac

### Describe the Bug

Following command 
```bash
NODE_ENV=production pnpm wrangler pages functions build ./functions --outfile build/_worker.js --output-routes-path build/_routes.json
```

After the update from 2.10.0 to 2.16.0 adds the following data to generated _worker.js file

```
------formdata-undici-065195447536
Content-Disposition: form-data; name="metadata"

{"main_module":"functionsWorker-0.03917103574002345.js"}
------formdata-undici-065195447536
Content-Disposition: form-data; name="functionsWorker-0.03917103574002345.js"; filename="functionsWorker-0.03917103574002345.js"
Content-Type: application/javascript+module
```

And fails with 

```log
Run `npx wrangler pages functions build ./functions --outfile build/_worker.js --output-routes-path build/_routes.json` to use the local version directly.

🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
✘ [ERROR] 1 error(s) and 0 warning(s) when compiling Worker.



✘ [ERROR] Expected ";" but found ":"

    _worker.js:2:19:
      2 │ Content-Disposition: form-data; name="metadata"
        │                    ^
        ╵                    ;


✘ [ERROR] Build failed with 1 error:

  _worker.js:2:19: ERROR: Expected ";" but found ":"


 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by fubhy** [comment]
We are seeing this too.

**Comment by bruceharrison1984** [comment]
I'm also seeing this on `3.1.2` when running with NPM. Is there an alternative to using this command to build the functions?

**Comment by CarmenPopoviciu** [comment]
hi folks, thank you for raising this issue 🙏 

Please be aware that `pages functions build` is not an external facing API, and we do not plan to support it as such in the foreseeable future. This command is meant to be used for our internal purposes alone, and we therefore do not recommend users to create any sort of dependency on it for production code.

Please refer [here](https://developers.cloudflare.com/workers/wrangler/commands/#pages) for the list of external facing commands that Pages supports.

Having said that, I did run the command in latest wrangler version `3.52.0` and am not seeing any similar errors as those reported in this issue. I am running:

- `npx wrangler pages functions build --build-output-directory=[directory]`, where the `[directory]` contains all static files, incl. `_worker.js`
- `npx wrangler pages functions build [functionsDirectory]`, where `[functionsDirectory]` is the directory containing all my functions.

Closing this as won't fix due to API not being external facing
