### ISSUE TITLE
🐛 BUG: stripe not working in page functions

### ISSUE THREAD

**Issue by mikob** [cloudflare/workers-sdk#2181]
### What version of `Wrangler` are you using?

2.1.15 (also 2.2.2)

### What operating system are you using?

Linux

### Describe the Bug

Need stripe webhooks - it's a common use-case. AFAIK stripe should work as it works in cloudflare workers? https://blog.cloudflare.com/announcing-stripe-support-in-workers/

I also tried with `--node-compat` (`wrangler pages dev ./dist --node-compat`) but that brought about some strange internal errors with crypto signing.

```ts
// functions/hooks/payment.ts
import stripe from "stripe";

export async function onRequestPost({ env, request }) {
    // Match the raw body to content type application/json
    const sig = request.headers.get("stripe-signature");
    const body = await request.text();
    let event: Stripe.Event;
    try {
        event = stripe.webhooks.constructEvent(
            body,
            sig,
            env.STRIPE_WEBHOOK_SIGNING_SECRET
        );
    } catch (err: any) {
        console.error(err);
        return new Response(`Webhook Error: ${err.message}`, {
            status: 400,
        });
    }
    return new Response(JSON.stringify({ received: true }), {
        headers: {
            "Content-Type": "application/json;charset=utf-8",
        },
    });
}
```

Commands
`npm add stripe`
`wrangler pages dev ./dist`

Output
```
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/clo
udflare/wrangler2/issues/new/choose
▲ [WARNING] No compatibility_date was specified. Using today's date: 2022-11-15.

  Pass it in your terminal:

  --compatibility-date=2022-11-15

  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.


Compiling worker to "/tmp/functionsWorker-0.43775990890548866.js"...
✘ [ERROR] Could not resolve "crypto"

    node_modules/.pnpm/stripe@10.17.0/node_modules/stripe/lib/crypto/NodeCryptoProvider.js:2:23:
      2 │ const crypto = require('crypto');
        ╵                        ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "crypto"

    node_modules/.pnpm/stripe@10.17.0/node_modules/stripe/lib/utils.js:4:23:
      4 │ const crypto = require('crypto');
        ╵                        ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "http"

    node_modules/.pnpm/stripe@10.17.0/node_modules/stripe/lib/net/NodeHttpClient.js:2:21:
      2 │ const http = require('http');
        ╵                      ~~~~~~

  The package "http" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "https"

    node_modules/.pnpm/stripe@10.17.0/node_modules/stripe/lib/net/NodeHttpClient.js:3:22:
      3 │ const https = require('https');
        ╵                       ~~~~~~~

  The package "https" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

4 error(s) and 0 warning(s) when compiling Worker.

✘ [ERROR] Build failed with 4 errors:

  node_modules/.pnpm/stripe@10.17.0/node_modules/stripe/lib/crypto/NodeCryptoProvider.js:2:23:
  ERROR: Could not resolve "crypto"
  node_modules/.pnpm/stripe@10.17.0/node_modules/stripe/lib/net/NodeHttpClient.js:2:21: ERROR:
  Could not resolve "http"
  node_modules/.pnpm/stripe@10.17.0/node_modules/stripe/lib/net/NodeHttpClient.js:3:22: ERROR:
  Could not resolve "https"
  node_modules/.pnpm/stripe@10.17.0/node_modules/stripe/lib/utils.js:4:23: ERROR: Could not resolve
  "crypto"


If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/i
ssues/new/choose
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by rozenmd** [comment]
@mikob this might help: https://jross.me/verifying-stripe-webhook-signatures-cloudflare-workers/

**Comment by mikob** [comment]
@rozenmd thanks very much, the workaround works :+1:! For others doing this workaround, make sure to modify your build command to something like this: 

package.json
```
...
    "build": "[build your frontend...] && wrangler pages functions build --node-compat && cp _worker.js dist",
...
```

**Comment by Cherry** [comment]
Since Stripe version 11.10.0, `node_compat` is no longer needed and you can simply import it in Workers/Functions without issue, so this can probably be closed out 🎉

**Comment by mikob** [comment]
Confirmed working with Stripe 11.10+ without node_compat for me.
