### ISSUE TITLE
🐛 BUG: Cannot find module @cloudflare/vitest-pool-workers/dist/config/index.cjs 

### ISSUE THREAD

**Issue by ekrenzin** [cloudflare/workers-sdk#5730]
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

3.53.0 [Wrangler]

### What version of Node are you using?

20.9.0

### What operating system and version are you using?

Tested on both Mac Sonoma 14.1, Windows 11

### Observed behavior
Missing files when attempting to use the latest version of vitest-pool-workers

Observed files on v0.2.4:
![image](https://github.com/cloudflare/workers-sdk/assets/33398104/461ae7b3-7680-422a-af6a-b8a500224acb)

Observed files on v0.1.19:
![image](https://github.com/cloudflare/workers-sdk/assets/33398104/2e5eb6f7-cae1-49b7-9b0a-1cd558867993)

### Expected behavior
Followed this guide: https://blog.cloudflare.com/workers-vitest-integration
Expected config files to be possible to import:

```
// vitest.config.js
import { defineWorkersConfig } from "@cloudflare/vitest-pool-workers/config";

export default defineWorkersConfig({
  test: {
    poolOptions: {
      workers: {
        wrangler: { configPath: "./wrangler.toml" },
      },
    },
  },
});
```

### Steps to reproduce
Follow this post: https://blog.cloudflare.com/workers-vitest-integration

Alternatively, create a new dir, init npm project, install package with `npm i @cloudflare/vitest-pool-workers` and observe missing (or found) files depending on version

### Please provide any relevant error logs

Error when running vitest:
````
Error: Cannot find module 'PATH_REDACTED/node_modules/@cloudflare/vitest-pool-workers/dist/config/index.cjs'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1070:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1063:15)
    at resolveExports (node:internal/modules/cjs/loader:547:14)
    at Module._findPath (node:internal/modules/cjs/loader:621:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (PATH_REDACTED/vitest.config.js:26:21)
    at Module._compile (node:internal/modules/cjs/loader:1241:14) {
  code: 'MODULE_NOT_FOUND',
  path: 'PATH_REDACTED/node_modules/@cloudflare/vitest-pool-workers/package.json'
}
````

**Comment by jamesbirtles** [comment]
the files are there and working in 0.2.3, and as mentioned not in 0.2.4

**Comment by gerhardcit** [comment]
yes, same here. after upgrade from 0.2.3 to 0.2.4 this errors pops up.

**Comment by msubodh** [comment]
Same error. I am using "@cloudflare/vitest-pool-workers": "^0.4.7"

wondering why this is closed? Was a solution found or a bug fixed?

**Comment by matsuyama-k1** [comment]
same error
```
{
  "name": "durable-object-starter",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "deploy": "wrangler deploy",
    "dev": "wrangler dev",
    "start": "wrangler dev",
    "cf-typegen": "wrangler types"
  },
  "devDependencies": {
    "@cloudflare/vitest-pool-workers": "^0.6.2",
    "@cloudflare/workers-types": "^4.20250109.0",
    "jest": "^29.7.0",
    "typescript": "^5.5.2",
    "vitest": "2.1.8",
    "wrangler": "^3.60.3"
  },
  "dependencies": {
    "@cfworker/uuid": "^4.0.3"
  }
}

```

**Comment by matsuyama-k1** [comment]
I found that I had to change tsconfig,ts
https://developers.cloudflare.com/workers/testing/vitest-integration/get-started/write-your-first-test/#define-types

```
{
	"compilerOptions": {
		/* .... */
		"moduleResolution": "bundler",
		"types": ["@cloudflare/workers-types/2023-07-01", "@cloudflare/vitest-pool-workers"],
	}
}
```
