### ISSUE TITLE
🐛 BUG: An itty-router-openapi app stopped working with TypeError: o3.replace is not a function

### ISSUE THREAD

**Issue by willtemperley** [cloudflare/workers-sdk#4732]
### Which Cloudflare product(s) does this pertain to?

Uncertain

### What version(s) of the tool(s) are you using?

Wrangler 3.22.4

### What version of Node are you using?

v20.10.0

### What operating system are you using?

Mac

### Describe the Bug

An itty-router-openapi application I've been developing for a week stopped working today after upgrading from Wrangler 3.22.2 to 3.22.4.  I keep getting the error message: 

[wrangler:err] TypeError: o3.replace is not a function

I've provided a minimal reproduction, which is just the OpenAPI example created using `npm create cloudflare@latest`which I can no longer get to work. A deployed application fails with the same error. 

Strangely downgrading to 3.22.2 doesn't work, neither does deleting node_modules and reinstalling, restarting machine etc.
My node installation is vanilla LTS 20.10.

<img width="1331" alt="Screenshot 2024-01-10 at 14 28 39" src="https://github.com/cloudflare/workers-sdk/assets/92311/5b2a9a10-ef84-416b-997b-9adc4b2f381f">

### Please provide a link to a minimal reproduction

https://github.com/willtemperley/open-api-test

### Please provide any relevant error logs

open-api-test % npx wrangler dev                                                        
 ⛅️ wrangler 3.22.4
-------------------
⎔ Starting local server...
[wrangler:inf] Ready on http://localhost:59737
[wrangler:err] TypeError: o3.replace is not a function
    at null.<anonymous> (file:///Users/will/openapi-example/open-api-test/node_modules/@cloudflare/itty-router-openapi/dist/index.mjs:1:6075)
    at Object.fetch (file:///Users/will/openapi-example/open-api-test/node_modules/@cloudflare/itty-router-openapi/dist/index.mjs:1:6721)
    at __facade_modules_fetch__ (file:///Users/will/openapi-example/open-api-test/.wrangler/tmp/bundle-s5zAaN/middleware-loader.entry.ts:46:16)
    at __facade_invokeChain__ (file:///Users/will/openapi-example/open-api-test/node_modules/wrangler/templates/middleware/common.ts:53:9)
    at Object.next (file:///Users/will/openapi-example/open-api-test/node_modules/wrangler/templates/middleware/common.ts:50:11)
    at jsonError2 (file:///Users/will/openapi-example/open-api-test/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:30)
    at __facade_invokeChain__ (file:///Users/will/openapi-example/open-api-test/node_modules/wrangler/templates/middleware/common.ts:53:9)
    at __facade_invoke__ (file:///Users/will/openapi-example/open-api-test/node_modules/wrangler/templates/middleware/common.ts:63:9)
    at Object.fetch (file:///Users/will/openapi-example/open-api-test/.wrangler/tmp/bundle-s5zAaN/middleware-loader.entry.ts:114:11)
[wrangler:inf] GET / 500 Internal Server Error (635ms)
[wrangler:err] TypeError: o3.replace is not a function
    at null.<anonymous> (file:///Users/will/openapi-example/open-api-test/node_modules/@cloudflare/itty-router-openapi/dist/index.mjs:1:6075)
    at Object.fetch (file:///Users/will/openapi-example/open-api-test/node_modules/@cloudflare/itty-router-openapi/dist/index.mjs:1:6721)
    at __facade_modules_fetch__ (file:///Users/will/openapi-example/open-api-test/.wrangler/tmp/bundle-s5zAaN/middleware-loader.entry.ts:46:16)
    at __facade_invokeChain__ (file:///Users/will/openapi-example/open-api-test/node_modules/wrangler/templates/middleware/common.ts:53:9)
    at Object.next (file:///Users/will/openapi-example/open-api-test/node_modules/wrangler/templates/middleware/common.ts:50:11)
    at jsonError2 (file:///Users/will/openapi-example/open-api-test/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:30)
    at __facade_invokeChain__ (file:///Users/will/openapi-example/open-api-test/node_modules/wrangler/templates/middleware/common.ts:53:9)
    at __facade_invoke__ (file:///Users/will/openapi-example/open-api-test/node_modules/wrangler/templates/middleware/common.ts:63:9)
    at Object.fetch (file:///Users/will/openapi-example/open-api-test/.wrangler/tmp/bundle-s5zAaN/middleware-loader.entry.ts:114:11)
[wrangler:inf] GET /favicon.ico 500 Internal Server Error (252ms)

**Comment by rhutikcodes** [comment]
Any updates on this?

**Comment by willtemperley** [comment]
Looks like this is an itty-router-openapi issue

https://github.com/cloudflare/itty-router-openapi/issues/112

**Comment by G4brym** [comment]
This issue is fixed in the latest version of [itty-router-openapi v1.0.7](https://github.com/cloudflare/itty-router-openapi/releases/tag/v1.0.7)
