### ISSUE TITLE
🐛 BUG: cannot find bound D1 DB using wrangler 3.5.0 in pages app

### ISSUE THREAD

**Issue by BryceMehring** [cloudflare/workers-sdk#3756]
### Which Cloudflare product(s) does this pertain to?

D1, Pages

### What version(s) of the tool(s) are you using?

3.5.0 Wrangler

### What version of Node are you using?

18.14.2 on windows, 18.17.0 on github actions

### What operating system are you using?

Windows, Linux(github actions)

### Describe the Bug

Starting with version 3.5.0 my worker cannot find my bound D1 DB, downgrading to version 3.4.0 fixed that problem. I'm using the following command to publish to pages via github actions: `wrangler pages publish ./out --project-name $PROJECT_NAME --branch $BRANCH`. In the `out` directory I have a my pages code plus a single `_worker.js` file. The binding variable name is `DB`

**Comment by WalshyDev** [comment]
Hey,

This is now fixed :)

Thanks for the report!

**Comment by peterhirn** [comment]
Inserts still don't work for me using `wrangler v3.8`

```json
    {
      "message": [
        "TypeError: this.client.prepare is not a function"
      ],
      "level": "error",
      "timestamp": 1695192903817
    }
```

Works with `wrangler v3.4`
