### ISSUE TITLE
🐛 BUG: dyld: Symbol not found: _MTLCommonCounterClipperInvocations

### ISSUE THREAD

**Issue by drhino** [cloudflare/workers-sdk#4166]
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.13.0 [Wrangler]

### What version of Node are you using?

16.20.2

### What operating system are you using?

Mac

### Describe the Bug

`wrangler dev` fails on:
Mac OS X 10.13.6 (17G14042)
Node 16.20.2 + Wrangler 3.13.0

Wrangler 3.12.0 and 3.11.0 works fine.

If a workaround for the missing symbol is possible, great.
If not, close as wontfix (It's an old OS).

### Please provide any relevant error logs

⛅️ wrangler 3.13.0
-------------------
▲ [WARNING] The --assets argument is experimental and may change or break at any time

--------------------
💡 Recommendation: for development, use a preview D1 database rather than the one you'd use in production.
💡 Create a new D1 database with "wrangler d1 create <name>" and add its id as preview_database_id to the d1_database "DB" in your wrangler.toml
--------------------

Your worker has access to the following bindings:
- D1 Databases:
  - DB: workers-ai (...)
- AI:
  - Name: AI
dyld: Symbol not found: _MTLCommonCounterClipperInvocations
  Referenced from: /Volumes/T7-DATA/Documenten/www/serverless/workers/drhino/workers-ai/node_modules/@cloudflare/workerd-darwin-64/bin/workerd (which was built for Mac OS X 11.0)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Volumes/T7-DATA/Documenten/www/serverless/workers/drhino/workers-ai/node_modules/@cloudflare/workerd-darwin-64/bin/workerd
dyld: Symbol not found: _MTLCommonCounterClipperInvocations
  Referenced from: /Volumes/T7-DATA/Documenten/www/serverless/workers/drhino/workers-ai/node_modules/@cloudflare/workerd-darwin-64/bin/workerd (which was built for Mac OS X 11.0)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Volumes/T7-DATA/Documenten/www/serverless/workers/drhino/workers-ai/node_modules/@cloudflare/workerd-darwin-64/bin/workerd
✘ [ERROR] {

    source: 'ProxyController',
    cause: Error: write EPIPE
        at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
      errno: -32,
      code: 'EPIPE',
      syscall: 'write'
    },
    reason: 'Could not connect to InspectorProxyWorker'
  }

**Comment by admah** [comment]
@drhino thanks for filing this issue. We've identified some issues with the latest version of Wrangler (3.13.0) and are working on fixes. In the meantime, we recommend staying on Wrangler 3.12.0 (npm install wrangler@latest should point to 3.12.0).

**Comment by admah** [comment]
@drhino we have published a new version of Wrangler (3.13.1) that reverts the change that was causing issues. You should be able to update and develop your Worker as expected.

**Comment by drhino** [comment]
Great, thx! 👌
Verified to work on Mac 10.13.6, Node 16.20.2 and Wrangler 3.13.1
Closing.

**Comment by penalosa** [comment]
Reopening this while we investigate the root cause

**Comment by RamIdeas** [comment]
It looks like the cause of this error is the old OS. The error message mentions `workerd (which was built for Mac OS X 11.0)` and your OS is 10.13.6.

This issue is not related to startDevWorker so I will remove the label.

I will also close the issue as we won't fix this for an old OS outside of wrangler's minimum requirements https://developers.cloudflare.com/workers/wrangler/commands/#dev
